In [2]:
import numpy as np

## Identity Matrix


In [3]:
np.identity (4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
np.eye (3, k = 1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [7]:
np.eye (4, k = 2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.eye (3, k = -1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [10]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [11]:
a = np.arange (0, 11)

In [12]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
a [0]

0

In [14]:
a [-1]

10

In [15]:
a [4]

4

In [16]:
a [1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a [1:-1:2]

array([1, 3, 5, 7, 9])

In [18]:
a [:5]

array([0, 1, 2, 3, 4])

In [19]:
a [-5:]

array([ 6,  7,  8,  9, 10])

In [21]:
a [::-2]

array([10,  8,  6,  4,  2,  0])

In [22]:
a [5:]

array([ 5,  6,  7,  8,  9, 10])

## Multidimensional Arrays

In [23]:
f = lambda m, n: n + 10 * m

In [24]:
A = np.fromfunction (f, (6, 6), dtype = int)

In [25]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [27]:
a [-3:]

array([ 8,  9, 10])

In [28]:
a [:-3]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [29]:
f

<function __main__.<lambda>(m, n)>

In [30]:
A [:, 1] # The second column

array([ 1, 11, 21, 31, 41, 51])

In [31]:
A [1, :] # the second row

array([10, 11, 12, 13, 14, 15])

In [34]:
A [:3, :3] # upper half diagonal block matrix

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [35]:
B = A [1:5, 1:5]

In [36]:
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [37]:
B [:, :] = 0

In [38]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])