In [1]:
import numpy as np

In [2]:
np.ndarray?

Init signature: np.ndarray(self, /, *args, **kwargs)
Docstring:     
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer int

In [3]:
data = np.array ([[1,2], [3,4], [5,6]])

In [4]:
type (data)

numpy.ndarray

In [5]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

`ndim` Number of dimensions (axes)

In [6]:
data.ndim

2

`shape` A tuple that contains the number of elements (i.e., the length) for each dimension (axis) of the array.

In [7]:
data.shape

(3, 2)

`size` The total number of elements in the array.

In [8]:
data.size

6

`dtype` The data type of the elements in the array.

In [9]:
data.dtype

dtype('int64')

`nbytes` Number of bytes used to store the data.

In [10]:
data.nbytes

48

## Data Types

Selecting datatypes when creating `np.ndarray`

In [11]:
np.array ([1, 2, 3], dtype = np.int)

array([1, 2, 3])

In [12]:
np.array ([1, 2, 3], dtype = np.float)

array([1., 2., 3.])

In [13]:
np.array ([1, 2, 3], dtype = np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

Once a NumPy array is created, its dtype cannot be changed, other than by creating a new copy with type-casted array values.

In [14]:
data = np.array ([1, 2, 3], dtype = np.float)

In [15]:
data

array([1., 2., 3.])

In [16]:
data.dtype

dtype('float64')

In [17]:
data = np.array (data, dtype = np.int)

In [18]:
data.dtype

dtype('int64')

In [19]:
data

array([1, 2, 3])

or by using the `astype` attribute

In [20]:
data = np.array ([1, 2, 3], dtype = float)

In [21]:
data

array([1., 2., 3.])

In [22]:
data.astype (np.int)

array([1, 2, 3])

The data type may get promoted to another if the operation requires it.

In [23]:
d1 = np.array ([1, 2, 3], dtype = float)

In [24]:
d2 = np.array ([1, 2, 3], dtype = complex)

In [25]:
d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [26]:
(d1 + d2).dtype

dtype('complex128')

Sometimes it's appropriate to set the dtype according to the application and its requirements.

In [27]:
np.sqrt (np.array ([-1, 0, 1]))

/Users/deon/anaconda3/envs/datasci/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([nan,  0.,  1.])

In [28]:
np.sqrt (np.array ([-1, 0, 1], dtype = complex))

array([0.+1.j, 0.+0.j, 1.+0.j])

Only when the data type of the array is complex is the square root of -1 giving in the imaginary unit (denoted as 1j in Python)

## Order of Array Data in Memory
A NumPy array can be specified to be stored in row-major format, using the keyword argument order='C', and column-major format, using the keyword argument order='F', when the array is created or reshaped.

C is for C and F is for Fortran.

## Real and Imaginary Parts

Regardless of the value of the dtype attribute, all NumPy array instances have the attributes real and imag for extracting the real and imaginary parts of the array, respectively:

In [29]:
data = np.array ([1, 2, 3], dtype = complex)

In [30]:
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [31]:
data.real

array([1., 2., 3.])

In [32]:
data.imag

array([0., 0., 0.])

Also provided by `np.real ()` and `np.imag ()`, which can be applied to other array-like objects, such as Python lists.

Python supports complex numbers and the `imag` and `real` attributes are available to Python scalars.

In [33]:
data.strides

(16,)

NumPy array attribute `ndarray.strides` defines exactly how this mapping is done. The strides attribute is a tuple of the same length as the number of axes (dimensions) of the array. Each value in strides is the factor by which the index for the corresponding axis is multiplied when calculating the memory offset (in bytes) for a given index expression.

## Creating Arrays
### Arrays Created from Lists and Other Array-like Objects
**There is an error in the text, in this section, that does not assign the newly created arrays to data, but calls attributes on data. Newly created np.arrays have been assigned to data in order to get the appropriate results.**

In [39]:
data = np.array ([1, 2, 3, 4])

In [40]:
data.ndim

1

In [41]:
data.shape

(4,)

To create a two-dimensional array...

In [42]:
data = np.array ([[1, 2], [3, 4]])

In [43]:
data.ndim

2

In [44]:
data.shape

(2, 2)

### Arrays Filled with Constant Values

In [46]:
np.zeros ((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.ones (4)

array([1., 1., 1., 1.])

dtype is `float64` by default, but accepts a keyword argument to change the dtype.

In [48]:
data = np.ones (4)

In [49]:
data.dtype

dtype('float64')

In [50]:
data = np.ones (4, dtype = np.int64)

In [51]:
data.dtype

dtype('int64')

In [52]:
x1 = 5.4 * np.ones (10)

In [53]:
x2 = np.full (10, 5.4)

In [54]:
x1

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [55]:
x2

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [56]:
x1 = np.empty (5)

In [57]:
x1.fill (3.0)

In [58]:
x1

array([3., 3., 3., 3., 3.])

In [59]:
x2 = np.full (5, 3.0)

In [60]:
x2

array([3., 3., 3., 3., 3.])

### Arrays Filled with Incremental Sequences

In [62]:
np.arange (0.0, 10, 1) # start, end, increment

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [63]:
np.linspace (0, 10, 11) # start, end, total number of points in array

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

`np.linspace` can exclude the enpoint with the `endpoint` keyword argument. Recommended to use `np.linspace` is recommended whenever the increment is a non-integer.

### Arrays Filled with Logarithmic Sequences

In [64]:
np.logspace (0, 2, 5) # 5 data points between 10 ** 0 = 1 to 10 ** 2 = 100

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

### Mesh-grid Arrays

In [65]:
x = np.array ([-1, 0, 1])

In [66]:
y = np.array ([-2, 0, 2])

In [67]:
X, Y = np.meshgrid (x, y)

In [68]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [69]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [70]:
Z = (X + Y) ** 2

In [71]:
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]])

### Creating Uninitialized Arrays

In [72]:
np.empty (3, dtype = np.float)

array([1., 2., 3.])

### Create Arrays with Properties of Other Arrays
Page 34

In [74]:
def f(x):
    y = np.ones_like (x)
    # compute with x and y
    return y